{"error":{"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"::","port":3000},"level":"error","message":"uncaughtException: listen EADDRINUSE: address already in use :::3000\nError: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (net.js:1290:14)\n    at listenInCluster (net.js:1338:12)\n    at Server.listen (net.js:1425:7)\n    at Function.listen (D:\\NodejS-API\\node_modules\\express\\lib\\application.js:618:24)\n    at Object.<anonymous> (D:\\NodejS-API\\server.js:31:5)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:282:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)","stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (net.js:1290:14)\n    at listenInCluster (net.js:1338:12)\n    at Server.listen (net.js:1425:7)\n    at Function.listen (D:\\NodejS-API\\node_modules\\express\\lib\\application.js:618:24)\n    at Object.<anonymous> (D:\\NodejS-API\\server.js:31:5)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:282:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)","exception":true,"date":"Sat Dec 29 2018 04:19:26 GMT+0700 (Indochina Time)","process":{"pid":1164,"uid":null,"gid":null,"cwd":"D:\\NodejS-API","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.14.2","argv":["C:\\Program Files\\nodejs\\node.exe","D:\\NodejS-API\\server.js"],"memoryUsage":{"rss":52666368,"heapTotal":39620608,"heapUsed":22903792,"external":128163}},"os":{"loadavg":[0,0,0],"uptime":83027},"trace":[{"column":14,"file":"net.js","function":"Server.setupListenHandle [as _listen2]","line":1290,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"net.js","function":"listenInCluster","line":1338,"method":null,"native":false},{"column":7,"file":"net.js","function":"Server.listen","line":1425,"method":"listen","native":false},{"column":24,"file":"D:\\NodejS-API\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":618,"method":"listen","native":false},{"column":5,"file":"D:\\NodejS-API\\server.js","function":null,"line":31,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":599,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":538,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":530,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":742,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":282,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":743,"method":null,"native":false}],"timestamp":"2018-12-28T21:19:26.426Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:53:32.489Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:53:32.493Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:53:42.802Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:53:42.803Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:54:20.099Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:54:20.101Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:54:45.580Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:54:45.582Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"3","origin":"DB","instance":{"accountNumber":3,"openDate":"2010-12-12T00:00:00.000Z","balance":"40000","customer_id":3},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"3"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);","level":"error","timestamp":"2018-12-29T03:59:23.041Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T03:59:23.061Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"3","origin":"DB","instance":{"accountNumber":3,"openDate":"2010-12-12T00:00:00.000Z","balance":"40000","customer_id":3},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"3"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);","level":"error","timestamp":"2018-12-29T04:00:13.177Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T04:00:13.179Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"2","origin":"DB","instance":{"accountNumber":2,"openDate":"2018-10-10T00:00:00.000Z","balance":"5000","customer_id":2},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"2"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (2,'2018-10-10 00:00:00','5000',2);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (2,'2018-10-10 00:00:00','5000',2);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (2,'2018-10-10 00:00:00','5000',2);","level":"error","timestamp":"2018-12-29T04:15:24.456Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T04:15:24.461Z"}
